### ISSUE TITLE
Could you provide the version of Kinetics dataset?

### ISSUE THREAD

**Issue by Yuuraa** [google/video-localized-narratives#3]
Hello :) Thank you for releasing your great work.

I wonder what version of Kinetics datset (400/600/700) did you used.
I tried Kinetics 400, but I couldn't find most of the video ids in narration annotations.

Thank you for oyur consideration

**Comment by pvoigtlaender** [comment]
Hi,

We used Kinetics 700.

Am Mi., 29. Nov. 2023 um 10:20 Uhr schrieb Yura Choi <
***@***.***>:

**Comment by Yuuraa** [comment]
Thak you :D!
